# Generated by Django 6.1.1 on 2026-09-22 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("academic_year", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("roll_number", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="cms.classroom",
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True, related_name="children", to="cms.parent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classroom",
            name="teachers",
            field=models.ManyToManyField(blank=True, to="cms.teacher"),
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("attendance_present", models.BooleanField(default=True)),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("happy", "Happy"),
                            ("good", "Good"),
                            ("normal", "Normal"),
                            ("tired", "Tired"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "morning_snack",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("finished", "Finished"),
                            ("partial", "Partly"),
                            ("did_not_eat", "Did Not Eat"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "lunch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("finished", "Finished"),
                            ("partial", "Partly"),
                            ("did_not_eat", "Did Not Eat"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rest_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slept", "Slept"),
                            ("rested", "Rested"),
                            ("did_not_rest", "Did Not Rest"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rest_start", models.TimeField(blank=True, null=True)),
                ("rest_end", models.TimeField(blank=True, null=True)),
                (
                    "participation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("participated", "Participated"),
                            ("partial", "Partially Participated"),
                            ("not_participated", "Not Participated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("teacher_observation", models.TextField(blank=True)),
                ("submitted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activities",
                    models.ManyToManyField(
                        blank=True, related_name="daily_reports", to="cms.activity"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="cms.child",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_reports",
                        to="cms.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "report_date"),
                        name="unique_child_daily_report",
                    )
                ],
            },
        ),
    ]
