# Generated by Django 6.1.1 on 2026-10-02 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyreport",
            name="arrival_time",
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="attendance_present",
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="departure_time",
        ),
    ]
